### ISSUE TITLE
不再尝试，已关闭

### ISSUE THREAD

**Issue by greenary-John** [guoday/Tencent2020_Rank1st#19]

**Comment by guoday** [comment]
忘了。不过按道理我这代码应该最新版本的都支持吧。好像没有哪个地方需要版本的要求。

**Comment by greenary-John** [comment]
谢谢

**Comment by greenary-John** [comment]
尊敬的作者，我确实无法独立解决gensim下无法解决代码的问题，
处理的过程中，我几乎替换了2018年以来所有的gensim版本和1.0.0以前的gensim(0.13)版本，还是无法解决这个问题
在此我把报错信息贴出来，希望得到大家的建议
#########以下为gensim 3.8,3.7,3.6版本下的报错信息：
Traceback (most recent call last):
  File "run.py", line 126, in <module>
    model.train(train_dataset,dev_dataset)
  File "/mnt/usb/data/guoleiming/competetion/tencent_ad2020/models/ctrNet.py", line 76, in train
    for step, batch in enumerate(train_dataloader):
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/usb/data/guoleiming/competetion/tencent_ad2020/src/data_loader.py", line 66, in __getitem__
    text_features_1[w_idx,begin_dim:end_dim]=embed_table[word]
  File "/home/hp/anaconda3/lib/python3.8/site-packages/gensim/models/keyedvectors.py", line 353, in __getitem__
    return self.get_vector(entities)
  File "/home/hp/anaconda3/lib/python3.8/site-packages/gensim/models/keyedvectors.py", line 471, in get_vector
    return self.word_vec(word)
  File "/home/hp/anaconda3/lib/python3.8/site-packages/gensim/models/keyedvectors.py", line 459, in word_vec
    if word in self.wv.vocab:
AttributeError: 'Word2VecKeyedVectors' object has no attribute 'vocab'


#########以下为gensim 4.0版本下的报错信息：
则报错信息为
05/15/2021 13:06:35 - INFO - __main__ -   Index: 0
05/15/2021 13:06:36 - INFO - models.ctrNet -   ***** Running training *****
05/15/2021 13:06:36 - INFO - models.ctrNet -     Num examples = 720000
05/15/2021 13:06:36 - INFO - models.ctrNet -     Num Epochs = 5
05/15/2021 13:06:36 - INFO - models.ctrNet -     Instantaneous batch size per GPU = 64
05/15/2021 13:06:36 - INFO - models.ctrNet -     Total train batch size (w. parallel, distributed & accumulation) = 64
05/15/2021 13:06:36 - INFO - models.ctrNet -     Total optimization steps = 56250
Traceback (most recent call last):
  File "run.py", line 126, in <module>
    model.train(train_dataset,dev_dataset)
  File "/mnt/usb/data/guoleiming/competetion/tencent_ad2020/models/ctrNet.py", line 76, in train
    for step, batch in enumerate(train_dataloader):
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/hp/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/mnt/usb/data/guoleiming/competetion/tencent_ad2020/src/data_loader.py", line 47, in __getitem__
    text_features[w_idx,begin_dim:end_dim]=embed_table[word]
TypeError: 'Word2Vec' object is not subscriptable
非常希望得到大家的建议
感谢，拜谢各位大佬了orz

**Comment by NickYi1990** [comment]
直接Google岂不更好，这是个包相关的问题
